---
- name: Deploy App with Docker
  hosts: ec2_instances
  become: yes  # Run tasks with elevated privileges (sudo)

  tasks:
    #* Docker installation
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true


    # Task 2: Start the Docker service
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    # Task 3: Pull Docker image from Docker Hub
    - name: Pull Docker image
      command: docker pull talibro/simple-java-maven-app:latest

    # Task 4: Run Docker container
    - name: Run Docker container
      command: docker run -d -p 8080:8080 talibro/simple-java-maven-app:latest

