name: Maven and Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Increment Patch Version
      run: |
        mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout).1
        git add pom.xml
        git commit -m "Increment patch version [skip ci]" || true
        git push origin main || true

    - name: Build and Push Docker Image
      run: |
        docker build -t talibro/simple-java-maven-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push talibro/simple-java-maven-app:latest

    - name: Push to GitHub
      run: |
        git push origin main
