name: Maven and Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Increment Patch Version
      run: |
        # Increment the patch version in the pom.xml file
        mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} \
          versions:commit
          
    - name: Run Tests
      run: |
        mvn test

    - name: Push Patch Version 
      run: |
        git config --global user.email "talibroder@gmail.com"
        git config --global user.name "talibroder"
        git add pom.xml
        git commit -m "Update version in pom.xml"
        git push origin master
        
    - name: Build and Push Docker Image
      run: |
        DOCKER_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        docker build -t talibro/simple-java-maven-app:${DOCKER_VERSION} -t talibro/simple-java-maven-app:latest .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push talibro/simple-java-maven-app:${DOCKER_VERSION}
        docker push talibro/simple-java-maven-app:latest
        
    - name: Push to GitHub
      run: |
        git push origin master

    - name: Set up Ansible
      uses: appleboy/ansible-action@v2
      with:
        path: ./ansible

    - name: Run Ansible playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/my_playbook.yml
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

